version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
    
      db-name: mydb1
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: Admin1234
    ports:
      - "3316:3306"

  app:
    build: .
    image: devteds/demo-bookstore-shopapi
    volumes:
      - .:/app/:rw
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      db-name: mydb1
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: Admin1234
      DB_HOST: mydb1.cj0xd5qbiilr.ap-south-1.rds.amazonaws.com

  # # Secrets from individual files on config/app_secret/*
  # app-prod:
  #   image: image: devteds/demo-bookstore-shopapi:1.0
  #   ports:
  #     - "3012:3000"
  #   volumes:
  #     - ./config/app_secret:/app/config/app_secret:ro
  #   depends_on:
  #     - db
  #   environment:
  #     DB_USER: root
  #     DB_NAME: bookstore
  #     DB_HOST: db
  #     RAILS_ENV: production
  #     RAILS_LOG_TO_STDOUT: "1"
