version: "3.4"

services:

  web:
    build:
      context: .
      # target: dev
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./:/web
    depends_on:
      - api  
    ports:
      - 8082:8080  
  
  # Backend API DB - Run locally
  api-db:
    image: mysql:5.7
    environment:
 db-name: mydb1
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: Admin1234
      
      
  # Backend API - Run locally. Container port 3000.
  # Web front-end dev proxy use http://api:3000 for /api/* requests
  api:
    image: devteds/demo-bookstore-shopapi:1.0
    environment:
 db-name: mydb1
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: Admin1234
      DB_HOST: mydb1.cj0xd5qbiilr.ap-south-1.rds.amazonaws.com
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "1"
    depends_on:
      - api-db
